# Generated by Django 3.2.13 on 2023-08-05 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0002_auto_20230804_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='status',
            new_name='estado',
        ),
    ]
